githubConfigUrl: https://github.com/meshachdamilare/rideshare-trip-service
githubConfigSecret: mh-github-secret

runnerScaleSetName: mh-runner-trip

minRunners: 1
maxRunners: 6

controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller

template:
  spec:
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command:
      - /home/runner/run.sh
      securityContext:
        runAsUser: 0
      env:
      - name: RUNNER_ALLOW_RUNASROOT
        value: "1"
      - name: BUILDKIT_HOST
        value: tcp://localhost:1234
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
    - name: buildkitd
      image: moby/buildkit:latest
      args:
      - --addr
      - tcp://0.0.0.0:1234
      securityContext:
        privileged: true
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
    volumes:
    - name: work
      emptyDir: {}
    restartPolicy: Never
