githubConfigUrl: https://github.com/meshachdamilare/mesh-github-runner
githubConfigSecret: mh-github-secret

runnerScaleSetName: mh-runner-set

minRunners: 1
maxRunners: 6

controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller

template:
  spec:
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command:
      - /home/runner/run.sh
    restartPolicy: Never
